### PR TITLE
Update Min SDK version on 21

### PR DESCRIPTION
**Pull request by taylorwinfield**
Updates the min required sdk version on Android to 21 to fix issues with multidex when building.

### CODE REVIEW

**Comment by ArmandoAssuncao** [comment]
Hi @taylorwinfield 

What's the issue with multidex?

**Comment by taylorwinfield** [comment]
Hey @ArmandoAssuncao 

I'm constantly getting issues building on this end saying the .dex file can't exceed 64k lines. I've tried adding all the suggested options to buildConfig but react-native-cli still doesn't respect those values when I run from the command line, very strange. Bumping the min SDK to 21 (Android 5) which uses the [ART runtime](https://developer.android.com/studio/build/multidex) with native mutiple dex support seems to be the only way to consistently fix it.

Any ideas?

**Comment by ArmandoAssuncao** [comment]
@taylorwinfield 

Could you show the your `build.gradle` with multidex configured? or/and create um example project with this issue?

**Comment by taylorwinfield** [comment]
Sure thing, this is what our `build.gradle` looks like, I'm using product flavors to specify different application id suffixes for different environments.

```
apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js"
]

apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"
apply from: "../../node_modules/react-native/react.gradle"
apply plugin: 'io.fabric'

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 27
    buildToolsVersion "27.0.3"

    defaultConfig {
        applicationId "com.xx"
        minSdkVersion 21
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        resValue "string", "build_config_package", "com.xx"
        testBuildType System.getProperty ('testBuildType', 'release') // this will later be used to control the test apk build type
        missingDimensionStrategy "minReactNative", "minReactNative46" // read note
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    flavorDimensions 'version'
    productFlavors {
        dev {
            dimension 'version'
            applicationIdSuffix ".dev"
        }
        stage {
            dimension 'version'
            applicationIdSuffix ".stage"
        }
        prod {
            dimension 'version'
        }
    }
    signingConfigs {
        release {
            storeFile file("../keystores/xxx.ks")
            storePassword "xxx"
            keyAlias "xxx"
            keyPassword "xxx"
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile project(':react-native-sqlite-2')
    compile project(':react-native-fs')
    implementation project(':react-native-config')
    implementation project(':react-native-ca-mas')
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.facebook.react:react-native:+'
    // From node_modules
    implementation('com.crashlytics.sdk.android:crashlytics:2.5.2@aar') {
        transitive = true;
    }
    androidTestImplementation project(path: ': detox')
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test:rules:1.0.2'
}

task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
```

Let me know what you think?

**Comment by ArmandoAssuncao** [comment]
@taylorwinfield 

I could not use your settings, but I usually fix the error: `.dex file can not exceed 64K.`, adding` multiDexEnabled true`. Have example in [troubleshooting](https://github.com/ArmandoAssuncao/react-native-ca-mas#troubleshooting).

If that does not work, could you create a test repo with this error?

**Comment by AnthonyWard** [comment]
It looks like using an SDK lower than 21 is quite a bit more involved than just using `multiDexEnabled true`: https://developer.android.com/studio/build/multidex#mdex-gradle

**Comment by taylorwinfield** [comment]
Closing this as I no longer have a need for Android SDK lower than 21 and the solution looks more involved than I expected.

**Pull request closed without merging**
